export const LETTERS = [
  { name: "A", example: "alligator", keycode: "65", src: "sounds/A.wav" },
  { name: "B", example: "bear", keycode: "66", src: "sounds/B.wav" },
  { name: "C", example: "cat", keycode: "67", src: "sounds/C.wav" },
  { name: "D", example: "dog", keycode: "68", src: "sounds/D.wav" },
  { name: "E", example: "elephant", keycode: "69", src: "sounds/E.wav" },
  { name: "F", example: "fish", keycode: "70", src: "sounds/F.wav" },
  { name: "G", example: "giraffe", keycode: "71", src: "sounds/G.wav" },
  { name: "H", example: "horse", keycode: "72", src: "sounds/H.wav" },
  { name: "I", example: "impala", keycode: "73", src: "sounds/I.wav" },
  { name: "J", example: "jellyfish", keycode: "74", src: "sounds/J.wav" },
  { name: "K", example: "koala", keycode: "75", src: "sounds/K.wav" },
  { name: "L", example: "leopard", keycode: "76", src: "sounds/L.wav" },
  { name: "M", example: "moose", keycode: "77", src: "sounds/M.wav" },
  { name: "N", example: "narwhal", keycode: "78", src: "sounds/N.wav" },
  { name: "O", example: "owl", keycode: "79", src: "sounds/O.wav" },
  { name: "P", example: "platypus", keycode: "80", src: "sounds/P.wav" },
  { name: "Q", example: "quail", keycode: "81", src: "sounds/Q.wav" },
  { name: "R", example: "reindeer", keycode: "82", src: "sounds/R.wav" },
  { name: "S", example: "snake", keycode: "83", src: "sounds/S.wav" },
  { name: "T", example: "turtle", keycode: "84", src: "sounds/T.wav" },
  { name: "U", example: "unicorn", keycode: "85", src: "sounds/U.wav" },
  { name: "V", example: "vulture", keycode: "86", src: "sounds/V.wav" },
  { name: "W", example: "walrus", keycode: "87", src: "sounds/W.wav" },
  { name: "X", example: "x-ray fish", keycode: "88", src: "sounds/X.wav" },
  { name: "Y", example: "yak", keycode: "89", src: "sounds/Y.wav" },
  { name: "Z", example: "zebra", keycode: "90", src: "sounds/Z.wav" },
];
